language: generic
sudo: false
cache:
  apt: true

env:
  global:
    - LIB_INSTALLDIR="$HOME"
    - AUDIERE_TAG=1.9.4
    - SPEEX_VER=1.1.9
    - SFML_TAG_CMDLINE=ZXhwb3J0IFNGTUxfVEFHPSQoY3VybCAtU3NMICdodHRwczovL2FwaS5naXRodWIuY29tL3JlcG9zL1NGTUwvU0ZNTC90YWdzP2NsaWVudF9pZD0kZ2hfYXBwX2lkJmNsaWVudF9zZWNyZXQ9JGdoX2FwcF9zZWNyZXQnIHwgcGVybCAtcGUgJ3MvW1s6c3BhY2U6XV0vL2cnIHwgcGVybCAtcGUgJ3MvXH1cfSxcey99fSxcbnsvZycgfCBwZXJsIC1wZSAncy8sLywgL2cnIHwgYXdrICd7cHJpbnQoJDMpfScgfCBzZWQgLWUgJ3MvXi4qIjoiLy9nJyAtZSAncy8iLC8vZycgLWUgJ3M6LzogLyA6ZycgfCBhd2sgJy9bWzpkaWdpdDpdLl0rJC8ge3ByaW50KCQxNCk7IGV4aXR9JykK
    - LD_LIBRARY_PATH="$LIB_INSTALLDIR/lib"

matrix:
  include:
    - env: CXX=g++-5 CC=gcc-5 DEPLOY=true
      addons:
        apt:
          packages:
            - g++-5
            - scons
            - libpthread-stubs0-dev
            - libgl1-mesa-dev
            - libx11-dev
            - libxrandr-dev
            - libfreetype6-dev
            - libglew-dev
            - libjpeg8-dev
            - libsndfile1-dev
            - libopenal-dev
            - libudev-dev
            - libx11-xcb-dev
            - libxcb-image0-dev
            - libxcb-randr0-dev
          sources: &sources
            - r-packages-precise
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
    - env: CXX=clang++-3.8 CC=clang-3.8
      addons:
        apt:
          packages:
            - clang-3.8
            - scons
            - libpthread-stubs0-dev
            - libgl1-mesa-dev
            - libx11-dev
            - libxrandr-dev
            - libfreetype6-dev
            - libglew-dev
            - libjpeg8-dev
            - libsndfile1-dev
            - libopenal-dev
            - libudev-dev
            - libx11-xcb-dev
            - libxcb-image0-dev
            - libxcb-randr0-dev
          sources: *sources

install:
  - export SFML_TAG_CMDLINE=$(base64 -d <<< $SFML_TAG_CMDLINE)
  - echo $SFML_TAG_CMDLINE; eval $SFML_TAG_CMDLINE
  - echo Using SFML ver $SFML_TAG
  - pushd "/tmp"
  - curl -SL https://github.com/SFML/SFML/archive/$SFML_TAG.tar.gz | tar -xzf-
  - cd "SFML-$SFML_TAG"
  - mkdir build && cd build
  - cmake -G"Unix Makefiles" .. -DCMAKE_INSTALL_PREFIX:PATH="$LIB_INSTALLDIR"
  - make -j$(nproc) install
  - popd
  -
  - pushd "/tmp"
  - curl -SL "http://downloads.xiph.org/releases/speex/speex-$SPEEX_VER.tar.gz" | tar -xzf-
  - cd "speex-$SPEEX_VER"
  - curl -SL "http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD" > config.sub
  - curl -SL "http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD" > config.guess
  - ./configure --prefix="$LIB_INSTALLDIR"
  - make -j$(nproc) install
  - popd
  -
  - pushd "/tmp"
  - curl -SL "http://kent.dl.sourceforge.net/project/audiere/audiere/$AUDIERE_TAG/audiere-$AUDIERE_TAG-src.tar.bz2" | tar -xjf-
  - mv "audiere" "audiere-$AUDIERE_TAG"
  - cd "audiere-$AUDIERE_TAG"
  - sed -i "s/'-Wno-non-virtual-dtor']/'-Wno-non-virtual-dtor'])\nif ARGUMENTS.has_key('CXXFLAGS'):\n  env.Append(CXXFLAGS=ARGUMENTS['CXXFLAGS'])\nif ARGUMENTS.has_key('LDFLAGS'):\n  env.Append(LINKFLAGS=ARGUMENTS['LDFLAGS'])\nenv.Append(LIBS='speex')/" SConstruct
  - sed -i 's:source = """:source = """\n\tsrc/dumb_resample.cpp\n\tsrc/input_speex.cpp\n\tsrc/speexfile/speexfile.cpp:' SConstruct
  - sed -i "s/#include <string>/#include <string>\n#include <cstring>/" src/audiere.h
  - sed -i "s/#include <stdio.h>/#include <stdio.h>\n#include <stdlib.h>/" src/debug.h
  - sed -i "s:#include <speex:#include <speex/speex:g" src/speexfile/speexfile.h
  - sed -i "s/#include <ctype.h>/#include <ctype.h>\n#include <stdio.h>/" src/utility.cpp
  # Doesn't work with `libFLAC.a` installed (gvia libflac-dev) either: https://travis-ci.org/nabijaczleweli/BarbersAndRebarbs/jobs/126249508#L709-L710
  # dumb is unavailable as package on Travis
  - scons CXXFLAGS="-isystem$LIB_INSTALLDIR/include -fpermissive" LDFLAGS="-L$LIB_INSTALLDIR/lib" use_flac=no use_dumb=no prefix="$LIB_INSTALLDIR" install
  - popd

script: ADDITIONAL_INCLUDE_DIR="$LIB_INSTALLDIR/include" ADDITIONAL_LINK_DIR="$LIB_INSTALLDIR/lib" make -j$(nproc)

before_deploy:
  - mkdir release
  - mv out/BarbersAndRebarbs.out out/BarbersAndRebarbs
  - cp -r out/BarbersAndRebarbs assets release/
  - LD_LIBRARY_PATH="$LIB_INSTALLDIR/lib" ldd release/BarbersAndRebarbs | awk '{print($3)}' | grep ".so" | xargs cp -t release/
  - strip --strip-all --remove-section=.comment --remove-section=.note release/BarbersAndRebarbs
  - mv release "BarbersAndRebarbs-$TRAVIS_TAG"
  - tar -caf "BarbersAndRebarbs-$TRAVIS_TAG.tbz2" "BarbersAndRebarbs-$TRAVIS_TAG"

deploy:
  provider: releases
  api-key:
    secure: ftpe/n5jmeu7Ad/Sxt5DxD/awQAz4oF9zSZ7ywpJF66ngsk9P9Q+ux063YlWz0gVZS7wy0blU8DG0Q1FpFt0/9oPBv/QhQwNAm61AX+XGVD/2MK7UGHvy8XWkYAG4STDP+v3PqrqAiQ+oS0+ku45RH47QFje5riWMOSDwsMkGEMeieEcoYUtdJtIUAPzetoHlCmO6Su40l3BQd5gLE+eyF+APeOIdg4mkTNu3IgZRhNG2has0vKRzcu5g29WcLrlIWsnybzl+kuWxfjFE2KAj3zoiVykqxReedypWRlp5Is+18G/AhGw0Gnvb+ktRxZQZ2lJVu0KnlKfyje3QFH6GTh14mtw2mJ07YAJnwDv8MBmPaPat57T8B17rOpjZCIGHUTw4MBLxjRx+es5slZYANnjEzLVx9lSw0p1c9JIIrR2/HuwWpN/BthabjLxAWdIvTgVyxQlCQidkCAdpO+D3SeDN1HxFooFG2mZkgWnjFjhfaYT8G0SF7fGO0oLAZzg1KneA+TjnlTU0nexLKi9Os89lJxdDv0sA9cayRxg5b51RO8rLAFGmtlc4aqJ0EFNN1HmXoMhQpIcQvGLOxYI/ogX8+rWaMOlYSI+9E4jH4kB6UPHP51ZKjYBRQkZpFOSooiMUKzuJVwz4+OYVSGDNGTuM2YrYC1ztTzps0d6ccY=
  file: "BarbersAndRebarbs-$TRAVIS_TAG.tbz2"
  skip_cleanup: true
  on:
    tags: true
    condition: $DEPLOY = true
